config/routes.rb
Rails.application.routes.draw do
  
  resources :students do
    resources :lessons
  end

  root "homepages#homepage"

  get "/lessons", to: "lessons#all_lessons"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :lessons
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepages_controller.rb
class HomepagesController < ApplicationController
	def homepage
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def all_lessons
    @lessons = Lesson.all

  end


  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @student = Student.all
  end

  def show
    @student = Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to students_path
    else
      render :new
    end
  end
  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    if @student.update(student_params)
      redirect_to students_path
    else
      render :edit
    end

  end

  def destroy
    @student = Student.find(params[:id])
    @student.delete
    redirect_to students_path
  end


private
  def student_params
    params.require(:student).permit(:name , :subject, :class_in_school, :location, :pay_by_hour, :other)  

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/homepages/homepage.html.erb
<h1>This is homepage CRM</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRMsamoz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <%= link_to 'HomePage', root_path, class: "nav-link text-white "  %>
            </li>
            <li class="nav-item">
              <%= link_to 'Students', students_path, class: "nav-link text-white " %>
            </li>
            <li class="nav-item">
              <%= link_to 'Lessons', lessons_path, class: "nav-link text-white " %>
            </li>

          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lessons/all_lessons.html.erb
<div class="d-flex flex-row bd-highlight">
	<div class = "m-2 p-2 bd-highlight">
		<h1>All lessons</h1>
	</div>
	<div class="bd-highlight m-2 p-2">
		<%= link_to 'New Leson', new_student_path , class: "btn btn-secondary btn-lg " %>

	</div>

</div>

app/views/lessons/edit.html.erb
<h1>Lessons#edit</h1>
<p>Find me in app/views/lessons/edit.html.erb</p>

app/views/lessons/index.html.erb
<h1>Lessons#index</h1>
<p>Find me in app/views/lessons/index.html.erb</p>

app/views/lessons/new.html.erb
<h1>Lessons#new</h1>
<p>Find me in app/views/lessons/new.html.erb</p>

app/views/lessons/show.html.erb
<h1>Lessons#show</h1>
<p>Find me in app/views/lessons/show.html.erb</p>

app/views/students/_form_for_new_student.html.erb
	 <%= form_with model: @student do |form| %>
	<div class="m-2 mb-0 p-2 border border-2 shadow-2">

		<div class="input-group mb-3">
		  <span class="input-group-text "  style="width: 120px;">Name</span>
		  <%= form.text_field :name ,class: "form-control", placeholder:"Name" %>
		</div>
		<div class="container ms-0"> 
			<div class="row">
				<div class="input-group mb-2 p-0" style="width: 25%;">
				  	<span class="input-group-text "  style="width: 120px;">Subject</span>
					<%= form.select :subject, ["Math", "Physics", "Math+Physics", "Math OGE", "Phys OGE", "Math EGE", "Phys EGE"],{}, class:"form-select" %>
		  		</div>
				<div class="input-group mb-2 "style="width: 25%;">
				  <span class="input-group-text" style="width: 120px;">Class</span>
					<%= form.select :class_in_school, (6..11).to_a , {} , class:"form-select" %>
				</div>
			</div>
			<div class="row"> 
				<div class="input-group mb-2 p-0" style="width: 25%;">
				  <span class="input-group-text "  style="width: 120px;">Location</span>
					<%= form.select :location, ["Online", "Home"], {} , class:"form-select" %>
				</div>
				<div class="input-group mb-2 " style="width: 25%;">
				  <span class="input-group-text " style="width: 120px;">Paybyhour</span>
				 <%= form.select :pay_by_hour, [700,800,900,1000] , {} , class:"form-select" %>
				</div>
			</div>
		</div>
		<div class="input-group mb-3">
				  <span class="input-group-text" id="basic-addon2" style="width: 120px;">Other</span>
				  <%= form.text_field :other ,class: "form-control", placeholder:"Other" %>
		</div>
	</div>
		<div class="mx-2  ">
            <%= form.submit "create!" , class:"mt-3 btn btn-outline-dark btn-lg" %>
		</div>
	 <% end %>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/edit.html.erb
<div>
	<div class="m-2  p-2 border border-2 shadow-2">
		<h1>Edit student</h1>
	</div>	
<%= render "form_for_new_student" %>

</div>

app/views/students/index.html.erb
<div class="d-flex flex-row bd-highlight">
	<div class = "m-2 p-2 bd-highlight">
		<h1>All students</h1>
	</div>
	<div class="bd-highlight m-2 p-2">
		<%= link_to 'New Student', new_student_path , class: "btn btn-secondary btn-lg " %>

	</div>

</div>




<div >
	<% @student.each do |student| %>

		<div class="border border-2 shadow-2 m-2 p-2">
			<div class="m-2 p-2">
				
			<h3 class="mb-3"> <%= student.name %></h3>
			<p> <%= student.subject %></p>
			

			</div>
			<div>
				<p>
					<%= link_to 'Show', student_path(student.id) , class: "btn btn-outline-primary btn-sm" %>
					<%= link_to 'Edit', edit_student_path(student.id), class: "btn btn-outline-secondary btn-sm" %>
					<%= link_to 'Delete', student_path(student.id), class: "btn btn-outline-dark btn-sm", method: :delete , data: { confirm: "are you shure?"} %>
				</p>
			</div>
			
		</div>
	<% end %>
</div>

app/views/students/new.html.erb
<div>
	<div class="m-2  p-2 border border-2 shadow-2">
		<h1>New student</h1>
	</div>	
<%= render "form_for_new_student" %>

</div>

app/views/students/show.html.erb
<div class="m-4 p-2 border border-2 shadow-2" >
	 
	<div class="mb-3">
		<h2> <%= @student.name %> </h2>
	</div>
	<div>
		<p> Subjecy : <%= @student.subject %></p>
		<p> Class : <%= @student.class_in_school %></p>
		<p> Pay_by_hour : <%= @student.pay_by_hour %></p>
		<p> Location : <%= @student.location %></p>
		<p> Other : <%= @student.other %></p>
	</div>
	
</div>